### PR TITLE
fix(server): correct dispatcher request method to use matchedPath

### LINKED ISSUE #585: ContextRegistry not finding closest path context, defaults to root due to Dispatcher bug
With an OpenApi v2 doc with a specific `basePath` the `contextRegistry.find` operation receives a path with the full `basePath` included. Since the contextRegistry entries do not include the basePath in their key it can't find any path-level contexts and defaults to the root context.

### PR DESCRIPTION
**Pull request by dethell-jh**
fixes #585 where the dispatcher needs the matchedPath passed to the contextRegistry find method so it does not include the api basePath.

### CODE REVIEW

File: src/server/dispatcher.ts [hunk 1]
```diff
@@ -70,7 +69,7 @@ export class Dispatcher {
   public constructor(
     registry: Registry,
     contextRegistry: ContextRegistry,
-    openApiDocument?: OpenApiDocument,
+    openApiDocument?: OpenApiDocument
```
Comment (ghost) [inline src/server/dispatcher.ts]: Sorry about all my linter-related changes. I can resubmit without those if you prefer.

File: src/server/dispatcher.ts [hunk 2]
```diff
@@ -242,18 +241,18 @@ export class Dispatcher {
     const response = await this.registry.endpoint(
       method,
       path,
-      this.parameterTypes(operation?.parameters),
+      this.parameterTypes(operation?.parameters)
     )({
       body,
-      context: this.contextRegistry.find(path),
+      context: this.contextRegistry.find(matchedPath),
```
Comment (ghost) [inline src/server/dispatcher.ts:248]: This is the only real change. Using `matchedPath` lets the `contextRegistry` find the given path among its entries.

File: src/server/dispatcher.ts (hunk 1 above)
Comment (pmcelhaney) [reply src/server/dispatcher.ts]: Ideally the linter wouldn't have made those kinds of changes in the first place. Did you run `yarn install` to make sure you have the latest version of Prettier? If that doesn't fix it, maybe we need to add a .prettierrc file to this repo?

**Comment by pmcelhaney** [comment]
Thanks! Can you fix the lint issues and add a unit test?

```ts
  it("passes a context object (not in the root)", async () => {
    const registry = new Registry();
    const contextRegistry = new ContextRegistry();

    contextRegistry.add("/", { id: "test context" });

    contextRegistry.add("/echo/{id}", { id: "echo context" });
    registry.add("/echo/{id}", {
      GET({ context }) {
        // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
        return { body: (context as { id: string }).id };
      },
    });

    const dispatcher = new Dispatcher(registry, contextRegistry);

    const result = await dispatcher.request({
      body: "",
      headers: {},
      method: "GET",
      path: "/echo/1",
      query: {},
      req: { path: "/echo/1" },
    });

    expect(result.body).toBe("echo context");
  });
```

**Review by pmcelhaney — CHANGES_REQUESTED** [review]

**Review by pmcelhaney — APPROVED** [review]
